sudo: required

language: rust

services:
  - docker

before_install:
- cat Dockerfile.test | docker build -t carrier-test-image -

script:
# We need to use 1 thread for the tests, because we reuse the same port.
- docker run --rm --user "$(id -u)":"$(id -g)" -v "$PWD":/src -w /src carrier-test-image cargo test --all -- --test-threads=1
